nis = (input("Masukan NIS anda : "))
nama = (input("Masukan Nama anda : "))
JK = (input("Masukan Jenis Kelamin anda : "))
rombel = (input("Masukan Rombel anda : "))
rayon = (input("Masukan Rayon anda : "))
TTL = (input("Masukan Tempat Lahir anda : "))
TGL = (input("Masukan Tanggal Lahir anda : "))
smp = (input("Masukan Asal SMP anda : "))
alamat = (input("Masukan Alamat anda : "))

print("=" * 25)
print("=" * 4, "Biodata Diri :", "=" * 4)
print("=" * 25)
print("NIS Anda : ", nis)
print("Nama Anda : ", nama)
print("Jenis Kelamin Anda : ", JK)
print("Rombel Anda : ", rombel)
print("Rayon Anda : ", rayon)
print("Tempat Lahir Anda : ", TTL)
print("Tanggal Lahir Anda : ", TGL)
print("Asal SMP Anda : ", smp)
print("Alamat Anda : ", alamat)
